version: '3.7'

services:

  oncare-front:
    container_name: oncare-front
    build:
      context: .
      dockerfile: Dockerfile
    image: doc_container_1

    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true